name = "crooked_beige_macaw-c438"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "crooked_beige_macaw-c438_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "crooked_beige_macaw-c438.wasm"
command = "npm run build:release"
